// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsTLDQRXPmwxy9jMMuTi-BbqlYwpiJHhY',
    appId: '1:1094781464620:web:3e1ca0a3c5494f6a40e189',
    messagingSenderId: '1094781464620',
    projectId: 'authin-c6b4f',
    authDomain: 'authin-c6b4f.firebaseapp.com',
    storageBucket: 'authin-c6b4f.appspot.com',
    measurementId: 'G-DK5GNEWXMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu9JQjDkw5y_E7OLDOZQCI38S0tWOpnF8',
    appId: '1:1094781464620:android:61f146d38c9af5a540e189',
    messagingSenderId: '1094781464620',
    projectId: 'authin-c6b4f',
    storageBucket: 'authin-c6b4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW8A63bT-cIxsspZVmZ4yQdfWs-3I0swQ',
    appId: '1:1094781464620:ios:b1f655952df6aada40e189',
    messagingSenderId: '1094781464620',
    projectId: 'authin-c6b4f',
    storageBucket: 'authin-c6b4f.appspot.com',
    iosClientId: '1094781464620-jpa53886ld3734de0p0j1qplfhrcfmoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.authin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW8A63bT-cIxsspZVmZ4yQdfWs-3I0swQ',
    appId: '1:1094781464620:ios:b1f655952df6aada40e189',
    messagingSenderId: '1094781464620',
    projectId: 'authin-c6b4f',
    storageBucket: 'authin-c6b4f.appspot.com',
    iosClientId: '1094781464620-jpa53886ld3734de0p0j1qplfhrcfmoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.authin',
  );
}
